services:
  fsw:
    extends:
      file: docker-compose-prod.yml
      service: fsw
    image: "cfs-dev"
    build:
      context: .
      dockerfile: cfs.Dockerfile
      target: "cfs-dev"
    volumes:
      - "./cFS:/code/cFS"
    working_dir: /code/cFS/build/exe/cpu2
  rosgsw:
    extends:
      file: docker-compose-prod.yml
      service: rosgsw
    image: "spaceros-brash-dev"
    build:
      # NOTE: Actual build process must be executed discretely for dev mounts
      context: .
      dockerfile: spaceros_brash.Dockerfile
      target: spaceros-brash-dev
    volumes:
      - "./brash:/code/brash"
      - "./cFS:/code/cFS"
      - "./juicer:/code/juicer"
    working_dir: /code/brash
  rosfsw:
    extends:
      file: docker-compose-prod.yml
      service: rosfsw
    image: "spaceros-brash-dev"
    build:
      context: .
      dockerfile: spaceros_brash.Dockerfile
      target: spaceros-brash-dev
    volumes:
      - "./brash:/code/brash"
    working_dir: /code/brash
  novnc:
    extends:
      file: docker-compose-prod.yml
      service: novnc

  pride:
    image: "pride-dev"
    command: >
      bash -c "sudo service mysql start 
      && sleep infinity"
    environment:
      - DISPLAY=novnc:0.0
    networks:
      spaceip:
        ipv4_address: 10.5.0.6
    build:
      # NOTE: Actual build process must be executed discretely for dev mounts
      context: .
      dockerfile: pride.Dockerfile
      target: pride-dev
      args:
        - USER_UID=${UID:-1000}
    volumes:
      - "./pride:/code/pride"
    working_dir: /code/pride

# NOTE: networks apparently can't be imported from related file?
networks:
  spaceip:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1

      
      
